### ISSUE TITLE
Unsupported or missing image file

### ISSUE THREAD

**Issue by hitesha14** [btcrabb/SlideSeg#8]
I  tried to use SlideSeg to segment whole slide images. My Image files are in tiff format. I encountered Unsupported or Missing Image file error while trying to do so. I have cross verified my filename, pathname etc. Everything seems to be correct. I have installed all library dependencies as well. Here is the stack trace of my error.

running __main__ with parameters: {'save_ratio': 'inf', 'format': 'jpg', 'tags': '1', 'slide_path': 'images/', 'overlap': '1', 'save_all': 'False', 'xml_path':'xml/', 'output_dir': 'output/', 'key': 'Annotation_Key.txt', 'print': '0', 'quality': '95', 'size': '128'}
SplitImagesoutput4000_18900.tif loading SplitImagesoutput4000_18900.tif Traceback (most recent call last):
 File "main.py", line 32, in <module>
    main()
  File "main.py", line 28, in main
    slideseg.run(params, filename)
  File "C:\Users\hits\Anaconda3\envs\SlideSeg\SlideSeg-master\SlideSeg-master\sl
ideseg.py", line 503, in run
    _osr, _levels, _dims = openwholeslide('{0}{1}'.format(_slide_path, filename)
)
  File "C:\Users\hits\Anaconda3\envs\SlideSeg\SlideSeg-master\SlideSeg-master\sl
ideseg.py", line 383, in openwholeslide
    osr = OpenSlide(path)
  File "C:\Users\hits\Anaconda3\envs\SlideSeg\lib\site-packages\openslide\__init
__.py", line 154, in __init__
    self._osr = lowlevel.open(filename)
  File "C:\Users\hits\Anaconda3\envs\SlideSeg\lib\site-packages\openslide\lowlev
el.py", line 174, in _check_open
    
"Unsupported or missing image file")
openslide.lowlevel.OpenSlideUnsupportedFormatError: Unsupported or missing image
 file

Please look into it . Thank you

**Comment by btcrabb** [comment]
SlideSeg uses OpenSlide to load and view whole slide images. Currently, only whole slide images that are supported by OpenSlide can be processed by SlideSeg at this time. The error you are getting is not part of the SlideSeg's code; instead, it is coming from openslide's lowlevel.py script. Since it appears your path variables and filename are correct, I recommend that you try to open the whole slide image using OpenSlide's deepzoom example to ensure that the .tif file can be open and viewed by OpenSlide.  

The filename of your .tif file suggests it has be processed by another script already. Ensure that it is still a single-file pyramidal tiled TIFF, which should be supported by OpenSlide as mentioned on https://openslide.org/formats/. 

Hope that helps!

**Comment by hitesha14** [comment]
As suggested by you I have used single-file pyramidal tiled TIFF, the code worked. Thank you the code worked.

**Comment by SenhorUnk** [comment]
I am currently facing the same error with the viewer tool QuPath and a MONAI Label Plugin for QuPath, which makes use of OpenSlide. I tried different image formats (tiff, svs, jpg, png). You can find the error message below: 

"[2022-10-06 09:24:00,412] [17916] [MainThread] [ERROR] (uvicorn.error:369) - Exception in ASGI application
Traceback (most recent call last):
  File "C:\UserData\z004muey\Documents\04_VS_Code_Workspace\MONAI_Label\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\UserData\z004muey\Documents\04_VS_Code_Workspace\MONAI_Label\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\UserData\z004muey\Documents\04_VS_Code_Workspace\MONAI_Label\lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\UserData\z004muey\Documents\04_VS_Code_Workspace\MONAI_Label\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\UserData\z004muey\Documents\04_VS_Code_Workspace\MONAI_Label\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\UserData\z004muey\Documents\04_VS_Code_Workspace\MONAI_Label\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\UserData\z004muey\Documents\04_VS_Code_Workspace\MONAI_Label\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\UserData\z004muey\Documents\04_VS_Code_Workspace\MONAI_Label\lib\site-packages\starlette\exceptions.py", line 93, in __call__
    raise exc
  File "C:\UserData\z004muey\Documents\04_VS_Code_Workspace\MONAI_Label\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "C:\UserData\z004muey\Documents\04_VS_Code_Workspace\MONAI_Label\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\UserData\z004muey\Documents\04_VS_Code_Workspace\MONAI_Label\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\UserData\z004muey\Documents\04_VS_Code_Workspace\MONAI_Label\lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "C:\UserData\z004muey\Documents\04_VS_Code_Workspace\MONAI_Label\lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "C:\UserData\z004muey\Documents\04_VS_Code_Workspace\MONAI_Label\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\UserData\z004muey\Documents\04_VS_Code_Workspace\MONAI_Label\lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "C:\UserData\z004muey\Documents\04_VS_Code_Workspace\MONAI_Label\lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\UserData\z004muey\Documents\04_VS_Code_Workspace\MONAI_Label\lib\site-packages\monailabel\endpoints\wsi_infer.py", line 113, in api_run_wsi_inference
    return run_wsi_inference(background_tasks, model, image, session_id, wsi, output)
  File "C:\UserData\z004muey\Documents\04_VS_Code_Workspace\MONAI_Label\lib\site-packages\monailabel\endpoints\wsi_infer.py", line 97, in run_wsi_inference
    result = instance.infer_wsi(request)
  File "C:\UserData\z004muey\Documents\04_VS_Code_Workspace\MONAI_Label\lib\site-packages\monailabel\interfaces\app.py", line 658, in infer_wsi
    infer_tasks = create_infer_wsi_tasks(request, image)
  File "C:\UserData\z004muey\Documents\04_VS_Code_Workspace\MONAI_Label\lib\site-packages\monailabel\interfaces\utils\wsi.py", line 43, in create_infer_wsi_tasks
    with openslide.OpenSlide(image) as slide:
  File "C:\UserData\z004muey\Documents\04_VS_Code_Workspace\MONAI_Label\lib\site-packages\openslide\__init__.py", line 160, in __init__
    self._osr = lowlevel.open(filename)
  File "C:\UserData\z004muey\Documents\04_VS_Code_Workspace\MONAI_Label\lib\site-packages\openslide\lowlevel.py", line 128, in _check_open
    raise OpenSlideUnsupportedFormatError(
openslide.lowlevel.OpenSlideUnsupportedFormatError: Unsupported or missing image file"
